### ISSUE TITLE
a_crash doesn't panic properly on ckb-vm

### ISSUE THREAD

**Issue by XuJiandong** [xxuejie/musl#2]
https://github.com/xxuejie/musl/blob/f122fb1d2743e73ad777f3dca027717738b2d3f3/src/internal/atomic.h#L250

It is valid on ckb-vm sometime.

**Comment by xxuejie** [comment]
Fixed in https://github.com/xxuejie/musl/commit/33d2b5abf56e580f2bf898f37a7196b3de9634ca
